
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class Hall1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Hall1
     */
    String HallID="";
    public Hall1() {
        initComponents();
        filltable();
    }

    void filltable()
    {
        Vector headings=new Vector();
        headings.add("HallID");
        headings.add("HallName");
        headings.add("NoofSeats");
        Vector data=new Vector();
         try{  
          Class.forName("oracle.jdbc.OracleDriver");
          String s1="jdbc:oracle:thin:@localhost:1522:";
          
          Connection con = DriverManager.getConnection(s1,"aditi","modgil");
          
          
          String query="select * from HALL";
          PreparedStatement p=con.prepareStatement(query);
          ResultSet rs=p.executeQuery();
          String HallID,HallName,NoofSeats;
          while(rs.next())
          {
              HallID=rs.getString("Hall_ID");
              HallName=rs.getString("Hall_Name");
              NoofSeats=rs.getString("No_of_Seats");
              Vector row=new Vector();
              row.add(HallID);
              row.add(HallName);
              row.add(NoofSeats);
              data.add(row);
              
          } 
          DefaultTableModel t = new DefaultTableModel(data,headings);
           jTable1.getModel();
           jTable1.setModel(t);
           con.close();
      }
      catch(Exception ex)
      {
          ex.printStackTrace();
          
          
      }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ht1 = new javax.swing.JTextField();
        ht2 = new javax.swing.JTextField();
        hb1 = new javax.swing.JButton();
        hb2 = new javax.swing.JButton();
        hb3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ht3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("   HALL ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("HALL ID");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("HALL NAME");

        ht2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ht2ActionPerformed(evt);
            }
        });

        hb1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hb1.setText("ADD");
        hb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hb1ActionPerformed(evt);
            }
        });

        hb2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hb2.setText("MODIFY");
        hb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hb2ActionPerformed(evt);
            }
        });

        hb3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hb3.setText("DELETE");
        hb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hb3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("NO. OF ROWS");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(hb1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(hb2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hb3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ht1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ht2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ht3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ht1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ht2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ht3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(hb3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(hb2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(hb1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                        .addGap(33, 33, 33))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ht2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ht2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ht2ActionPerformed

    private void hb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hb1ActionPerformed
      try{  
          Class.forName("oracle.jdbc.OracleDriver");
          String s1="jdbc:oracle:thin:@localhost:1522:";
          String HallID=ht1.getText();
          String HallName=ht2.getText();
          String NoofSeats=ht3.getText();
          Connection con = DriverManager.getConnection(s1,"aditi","modgil");
          String query="insert into HALL values(?,?,?)";
          PreparedStatement p=con.prepareStatement(query);
          p.setString(1,HallID);
          p.setString(2,HallName);
          p.setString(3,NoofSeats);
          p.executeUpdate();
          System.out.println("Data Added");
          JOptionPane.showMessageDialog(this,"Data Added");
          filltable();
          con.close();
      }
      catch(Exception ex)
      {
          ex.printStackTrace();
          
          
      }
    }//GEN-LAST:event_hb1ActionPerformed

    private void hb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hb2ActionPerformed
          try{  
          Class.forName("oracle.jdbc.OracleDriver");
          String s1="jdbc:oracle:thin:@localhost:1522:";
          String HallID=ht1.getText();
          String HallName=ht2.getText();
          String NoofSeats=ht3.getText();
          Connection con = DriverManager.getConnection(s1,"aditi","modgil");
          String query = "update HALL set Hall_Name=?,No_of_Seats=? where Hall_ID=?";
          
          PreparedStatement p=con.prepareStatement(query);
          p.setString(3,HallID);
          p.setString(1,HallName);
          p.setString(2,NoofSeats);
          p.executeUpdate();
          System.out.println("Data Modified");
          JOptionPane.showMessageDialog(this,"Data Modified");
          filltable();
          con.close();
      }
      catch(Exception ex)
      {
          ex.printStackTrace();
          
          
      }
    }//GEN-LAST:event_hb2ActionPerformed

    private void hb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hb3ActionPerformed
         try{  
          Class.forName("oracle.jdbc.OracleDriver");
          String s1="jdbc:oracle:thin:@localhost:1522:";
          String HallID=ht1.getText();
          String HallName=ht2.getText();
          String NoofSeats=ht3.getText();
          Connection con = DriverManager.getConnection(s1,"aditi","modgil");
          String query = "delete HALL where Hall_ID=?";
          
          
          PreparedStatement p=con.prepareStatement(query);
          p.setString(1,HallID);
         // p.setString(1,HallName);
         // p.setString(2,NoofSeats);
          p.executeUpdate();
          System.out.println("Data Deleted");
          JOptionPane.showMessageDialog(this,"Data Deleted");
          filltable();
          con.close();
      }
      catch(Exception ex)
      {
          ex.printStackTrace();
          
          
      }
    }//GEN-LAST:event_hb3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
int a=jTable1.getSelectedRow();
TableModel m1=jTable1.getModel();
String f=(String)m1.getValueAt(a,0);
ht1.setText(f);

String name=(String)m1.getValueAt(a,1);
ht2.setText(name);
String seats=(String)m1.getValueAt(a,2);
ht3.setText(seats);
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hb1;
    private javax.swing.JButton hb2;
    private javax.swing.JButton hb3;
    private javax.swing.JTextField ht1;
    private javax.swing.JTextField ht2;
    private javax.swing.JTextField ht3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
