
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class Rows extends javax.swing.JInternalFrame { 
    String HallID="";
    String RowID="";
    String rows;
    ArrayList halls;
    int flag=0;
    public Rows()
    {
        initComponents();
        filltable();
    }

    void filltable()
    {
        Vector headings=new Vector();
        headings.add("Hall");
        headings.add("Rows");
        headings.add("SeatsPerRow");
        Vector data=new Vector();
         try{  
          Class.forName("oracle.jdbc.OracleDriver");
          String s1="jdbc:oracle:thin:@localhost:1522:";
          
          Connection con = DriverManager.getConnection(s1,"aditi","modgil");
          
                  String query="select * from Rows_1";
          PreparedStatement p=con.prepareStatement(query);
          ResultSet rs=p.executeQuery();
          String HallID,Rows,SeatsPerRow;
          while(rs.next())
          {
              HallID=rs.getString("Hall_ID");
              rows=rs.getString("Row_No");
              SeatsPerRow=rs.getString("Seats_Per_Row");
              Vector row=new Vector();
              row.add(HallID);
              row.add(rows);
              row.add(SeatsPerRow);
              data.add(row);
              
          } 
          DefaultTableModel t = new DefaultTableModel(data,headings);
           jTable1.getModel();
           jTable1.setModel(t);
           con.close();
      }
      catch(Exception ex)
      {
          ex.printStackTrace();
          
          
      }
    }
    

  
    void fillhall()
{
    try
    {
     Class.forName("oracle.jdbc.OracleDriver");
          String s1="jdbc:oracle:thin:@localhost:1522:";
           Connection con = DriverManager.getConnection(s1,"aditi","modgil");
          String query="select * from hall";
          PreparedStatement p=con.prepareStatement(query); 
          ResultSet rs=p.executeQuery();
          halls=new ArrayList();
          while(rs.next())
          {
             
         rcb1.addItem(rs.getString("hall_name"));
         
         String hall[]=new String[2];
         hall[0]=rs.getString("hall_id");
         hall[1]=rs.getString("hall_name");
         halls.add(hall);
         
          }
          flag=0;
          
    }
    catch(Exception ex)
    {
        ex.printStackTrace();
    }
    
}
String filrows(String hallid)
{
    try
    {
        
     Class.forName("oracle.jdbc.OracleDriver");
          String s1="jdbc:oracle:thin:@localhost:1522:";
           Connection con = DriverManager.getConnection(s1,"aditi","modgil");
          String query="select * from hall where hall_id=?";
          PreparedStatement p=con.prepareStatement(query); 
          p.setString(1, hallid);
          ResultSet rs=p.executeQuery();
          if(rs.next())
          {
        rows=rs.getString("no_of_seats");
          }
    }
    catch(Exception ex)
    {
        ex.printStackTrace();
    }
    return rows;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rt1 = new javax.swing.JTextField();
        rcb1 = new javax.swing.JComboBox();
        rb1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        rcb2 = new javax.swing.JComboBox();
        rb2 = new javax.swing.JButton();
        rb3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("ROWS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Hall");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Seats Per Row");

        rcb1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rcb1ItemStateChanged(evt);
            }
        });
        rcb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcb1ActionPerformed(evt);
            }
        });

        rb1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rb1.setText("SAVE");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("No of Rows");

        rcb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcb2ActionPerformed(evt);
            }
        });

        rb2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rb2.setText("MODIFY");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });

        rb3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rb3.setText("DELETE");
        rb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rt1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rcb1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rcb2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(rb1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rb2)
                        .addGap(54, 54, 54)
                        .addComponent(rb3)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rcb1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rcb2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rt1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(rb1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
            try{  
          Class.forName("oracle.jdbc.OracleDriver");
          String s1="jdbc:oracle:thin:@localhost:1522:";
          int Hall=rcb1.getSelectedIndex();
          String hh[]=(String [])halls.get(Hall);
          String hallid=hh[0];
          
          int NoofRows=(Integer)rcb2.getSelectedItem();
         
          
          String SeatsPerRow=rt1.getText();
          
          Connection con = DriverManager.getConnection(s1,"aditi","modgil");
          String query="insert into Rows_1 values(?,?,?,?)";
          PreparedStatement p=con.prepareStatement(query);
                    p.setString(1,"");

          p.setString(2,hallid);
          p.setString(3,SeatsPerRow);
            p.setInt(4,NoofRows);
          p.executeUpdate();
          System.out.println("Data Saved");
          JOptionPane.showMessageDialog(this,"Data Saved");
          
          con.close();
      }
      catch(Exception ex)
      {
          ex.printStackTrace();
          
          
      }
    }//GEN-LAST:event_rb1ActionPerformed

    private void rcb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rcb2ActionPerformed

    private void rcb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rcb1ActionPerformed

    private void rcb1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rcb1ItemStateChanged
   
        if(flag!=1)
        {
            rcb2.removeAllItems();
         int Hall=rcb1.getSelectedIndex();
          String hh[]=(String [])halls.get(Hall);
          String hallid=hh[0];
       String rows1= filrows(hallid);
       int rowcount=Integer.parseInt(rows1);
       for(int i=1;i<=rowcount;i++)
       {
           rcb2.addItem(i);
       }
        }
        
        
        
        
        
    }//GEN-LAST:event_rcb1ItemStateChanged

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed

        try{  
          Class.forName("oracle.jdbc.OracleDriver");
          String s1="jdbc:oracle:thin:@localhost:1522:";
          int Hall=rcb1.getSelectedIndex();
          String hh[]=(String [])halls.get(Hall);
          String hallid=hh[0];
          
          
          
          
          int NoofRows=(Integer)rcb2.getSelectedItem();
         
          
          String SeatsPerRow=rt1.getText();
          
          Connection con = DriverManager.getConnection(s1,"aditi","modgil");
          String query="update Rows_1 set Seats_Per_Row=? where Row_ID=?";
          PreparedStatement p=con.prepareStatement(query);
          p.setString(2,hallid);
          p.setString(1,SeatsPerRow);
          
          p.executeUpdate();
          System.out.println("Data Modified");
          JOptionPane.showMessageDialog(this,"Data Modified");
          
          con.close();
      }
      catch(Exception ex)
      {
          ex.printStackTrace();
          
          
      }
                                       

    }//GEN-LAST:event_rb2ActionPerformed

    private void rb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3ActionPerformed
     try{  
          Class.forName("oracle.jdbc.OracleDriver");
          String s1="jdbc:oracle:thin:@localhost:1522:";
          int Hall=rcb1.getSelectedIndex();
          String hh[]=(String [])halls.get(Hall);
          String hallid=hh[0];
          
          
          
          
          int NoofRows=(Integer)rcb2.getSelectedItem();
         
          
          String SeatsPerRow=rt1.getText();
          
          Connection con = DriverManager.getConnection(s1,"aditi","modgil");
          String query="delete Rows_1 where Row_ID=?";
          PreparedStatement p=con.prepareStatement(query);
          p.setString(1,RowID);
         // p.setString(1,SeatsPerRow);
          
          p.executeUpdate();
          System.out.println("Data Deleted");
          JOptionPane.showMessageDialog(this,"Data Deleted");
          
          con.close();
      }
      catch(Exception ex)
      {
          ex.printStackTrace();
          
          
      }
                            
    }//GEN-LAST:event_rb3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       int a=jTable1.getSelectedRow();
TableModel m1=jTable1.getModel();
String f=(String)m1.getValueAt(a,0);


String rows=(String)m1.getValueAt(a,1);

String seats=(String)m1.getValueAt(a,2);
rt1.setText(seats);
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton rb1;
    private javax.swing.JButton rb2;
    private javax.swing.JButton rb3;
    private javax.swing.JComboBox rcb1;
    private javax.swing.JComboBox rcb2;
    private javax.swing.JTextField rt1;
    // End of variables declaration//GEN-END:variables
}
