
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class Shows extends javax.swing.JInternalFrame {

    /**
     * Creates new form Shows
     */
    ArrayList hallid;
    ArrayList movies;
    String movies1;
    int flag=0;
    public Shows() {
        initComponents();
        fillhall();
        filmovies();
        
        
    }
     void fillhall()
{
    try
    {
     Class.forName("oracle.jdbc.OracleDriver");
          String s1="jdbc:oracle:thin:@localhost:1522:";
           Connection con = DriverManager.getConnection(s1,"aditi","modgil");
          String query="select * from hall";
          PreparedStatement p=con.prepareStatement(query); 
          ResultSet rs=p.executeQuery();
          hallid=new ArrayList();
          while(rs.next())
          {
             
         scb1.addItem(rs.getString("hall_name"));
         
         String hall[]=new String[2];
         hall[0]=rs.getString("hall_id");
         hall[1]=rs.getString("hall_name");
         hallid.add(hall);
         
          }
          flag=0;
          
    }
    catch(Exception ex)
    {
        ex.printStackTrace();
    }
}
    void filmovies()
    {
    try
    {
        
     Class.forName("oracle.jdbc.OracleDriver");
          String s1="jdbc:oracle:thin:@localhost:1522:";
             Connection con = DriverManager.getConnection(s1,"aditi","modgil");
          String query="select * from movies";
          PreparedStatement p=con.prepareStatement(query); 
        
          ResultSet rs=p.executeQuery();
           movies=new ArrayList();
          while(rs.next())
          {
              
         scb2.addItem(rs.getString("movie_name"));
         
         String movie[]=new String[2];
         movie[0]=rs.getString("movie_id");
        movie[1]=rs.getString("movie_name");
         movies.add(movie);
         
          }
          flag=0;
    }
    catch(Exception ex)
    {
        ex.printStackTrace();
    }
    
}
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        scb1 = new javax.swing.JComboBox();
        scb2 = new javax.swing.JComboBox();
        st1 = new javax.swing.JTextField();
        st2 = new javax.swing.JTextField();
        sb1 = new javax.swing.JButton();
        sb2 = new javax.swing.JButton();
        sb3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        st3 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("SHOWS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Halls");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Movies");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Start Time");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("End Time");

        scb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scb1ActionPerformed(evt);
            }
        });

        sb1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sb1.setText("SAVE");
        sb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sb1ActionPerformed(evt);
            }
        });

        sb2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sb2.setText("MODIFY");
        sb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sb2ActionPerformed(evt);
            }
        });

        sb3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sb3.setText("DELETE");
        sb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sb3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sb2)
                                .addGap(71, 71, 71)
                                .addComponent(sb3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(3, 3, 3)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(scb1, 0, 61, Short.MAX_VALUE)
                                                .addComponent(scb2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addComponent(st1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(st2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(st3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(sb1)))
                .addContainerGap(357, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(scb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(st3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(st2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(sb1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sb2)
                            .addComponent(sb3))
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(st1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sb3ActionPerformed
         try{  
          Class.forName("oracle.jdbc.OracleDriver");
          String s1="jdbc:oracle:thin:@localhost:1522:";
          int Halls=scb1.getSelectedIndex();
          String hh[]=(String [])hallid.get(Halls);
          String hallid=hh[0];
          
          int Movies=scb2.getSelectedIndex();
          String mm[]=(String[])movies.get(Movies);
          String movieid=mm[0];
         
          
          String StartTime=st1.getText();
          String EndTime=st2.getText();
          String Date=st3.getText();
          Connection con = DriverManager.getConnection(s1,"aditi","modgil");
          String query="delete Shows where Hall_ID=?";
          PreparedStatement p=con.prepareStatement(query);
                    
                    p.setString(1,hallid);
                    
                    
                  
                    p.executeUpdate();

          System.out.println("Data Deleted");
          JOptionPane.showMessageDialog(this,"Data Deleted");
          
          con.close();
      }
      catch(Exception ex)
      {
          ex.printStackTrace();
          
          
      }
    }//GEN-LAST:event_sb3ActionPerformed

    private void sb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sb1ActionPerformed
         try{  
          Class.forName("oracle.jdbc.OracleDriver");
          String s1="jdbc:oracle:thin:@localhost:1522:";
          int Halls=scb1.getSelectedIndex();
          String hh[]=(String [])hallid.get(Halls);
          String hallid=hh[0];
          
          int Movies=scb2.getSelectedIndex();
          String mm[]=(String[])movies.get(Movies);
          String movieid=mm[0];
         
          String Date=st3.getText();
          String StartTime=st1.getText();
          String EndTime=st2.getText();
          Connection con = DriverManager.getConnection(s1,"aditi","modgil");
          String query="insert into Shows values(?,?,?,?,?)";
          PreparedStatement p=con.prepareStatement(query);
                    p.setString(1,"");
                    p.setString(2,hallid);
                    p.setString(3,movieid);
                    p.setString(4,Date);
                    p.setString(5,StartTime);
                    p.setString(6,EndTime);
                    p.executeUpdate();

          System.out.println("Data Saved");
          JOptionPane.showMessageDialog(this,"Data Saved");
          
          con.close();
      }
      catch(Exception ex)
      {
          ex.printStackTrace();
          
          
      }
                              
    }//GEN-LAST:event_sb1ActionPerformed

    private void sb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sb2ActionPerformed
     try{  
          Class.forName("oracle.jdbc.OracleDriver");
          String s1="jdbc:oracle:thin:@localhost:1522:";
          int Halls=scb1.getSelectedIndex();
          String hh[]=(String [])hallid.get(Halls);
          String hallid=hh[0];
          
          int Movies=scb2.getSelectedIndex();
          String mm[]=(String[])movies.get(Movies);
          String movieid=mm[0];
         
          
          String StartTime=st1.getText();
          String EndTime=st2.getText();
          String Date=st3.getText();
          Connection con = DriverManager.getConnection(s1,"aditi","modgil");
          String query="update Shows set Start_Time=?,End_Time=?,Date=? where Hall_ID=?";
          PreparedStatement p=con.prepareStatement(query);
                    
                    p.setString(3,Date);
                    p.setString(2,EndTime);
                    p.setString(1,StartTime);
                    p.setString(4,hallid);
                    
                    p.executeUpdate();

          System.out.println("Data Modified");
          JOptionPane.showMessageDialog(this,"Data Modified");
          
          con.close();
      }
      catch(Exception ex)
      {
          ex.printStackTrace();
          
          
      }
    }//GEN-LAST:event_sb2ActionPerformed

    private void scb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scb1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton sb1;
    private javax.swing.JButton sb2;
    private javax.swing.JButton sb3;
    private javax.swing.JComboBox scb1;
    private javax.swing.JComboBox scb2;
    private javax.swing.JTextField st1;
    private javax.swing.JTextField st2;
    private javax.swing.JTextField st3;
    // End of variables declaration//GEN-END:variables
}
